const mongoose=require('mongoose');

const ticketSchema=new mongoose.Schema({
    title: String,
    category: String,
    subcategory: String,
    date: Date,
    location: String,
    price: Number,
    owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },//stores objectId(autogenerated while we store the data of the user in User/owner in Ticket) of the owner from the User collection.foreign key. ref used to refer to User.doesn't store the entire data of user but only it's object id which is unique
    status: { type: String, default: 'available' },
});

module.exports=mongoose.model('Ticket',ticketSchema);

//populate can be used to access the entire data of the user/owner
//const a=await Ticket.find().populate('owner);
//console.log(a.owner.username); 